server:
  port: 8082
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:8180/realms/checklist-realm'
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: list-service
          uri: 'http://localhost:8081'
          predicates:
            - Path=/check-lists/**
