spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
