server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  application:
    name: list-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:8180/realms/checklist-realm'
